// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/button/index.vue')['default']
    Dialog: typeof import('./src/components/dialog/dialog.vue')['default']
    DialogCard: typeof import('./src/components/dialog/dialogCard.vue')['default']
    Form: typeof import('./src/components/native-ui/form/index.vue')['default']
    Item: typeof import('./src/components/native-ui/form/item.vue')['default']
    Modal: typeof import('./src/components/native-ui/modal/index.vue')['default']
    NCard: typeof import('naive-ui')['NCard']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NInput: typeof import('naive-ui')['NInput']
    NModal: typeof import('naive-ui')['NModal']
    NSwitch: typeof import('naive-ui')['NSwitch']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Table: typeof import('./src/components/table/index.vue')['default']
  }
}
